version: '3.3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 8111:8111
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
     app_net:
       ipv4_address: 192.168.1.2
    extra_hosts:
     - "node1:192.168.1.3"
     - "node2:192.168.1.4"

  web:
    image: php:7.2-apache
    ports:
     - 80:80
    volumes:
     - ./apache-html/httpd.conf:/usr/local/apache2/conf/httpd.conf
     - ./apache-html/:/var/www/html
    networks:
     app_net:
       ipv4_address: 192.168.1.3
    extra_hosts:
     - "node1:192.168.1.3"
     - "node2:192.168.1.4"
  web2:
    image: httpd
    volumes:
     - ./apache-html2/httpd.conf:/usr/local/apache2/conf/httpd.conf
     - ./apache-html2/:/var/www/html
    networks:
     app_net:
       ipv4_address: 192.168.1.4
    extra_hosts:
     - "node1:192.168.1.3"
     - "node2:192.168.1.4"

networks:
  app_net:
   driver: bridge
   ipam:
    config:
      - subnet: 192.168.1.0/24
